name: Standards  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /standards get lambda deploy zip
        uses: postman-open-technologies/standards@main
        with:
            args: zip -qq -r m-s-standards-g.zip standards/get/index.js node_modules
      - name: standard get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-standards-g
            zip_file: m-s-standards-g.zip
      - name: /standards post lambda deploy zip
        uses: postman-open-technologies/standards@main
        with:
            args: zip -qq -r m-s-standards-po.zip standards/post/index.js node_modules
      - name: standard get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-standards-po
            zip_file: m-s-standards-po.zip
      - name: /standards/{standard_id} get lambda deploy zip
        uses: postman-open-technologies/standards@main
        with:
            args: zip -qq -r m-s-standards-standard-g.zip standards/standard_id/get/index.js node_modules
      - name: standard get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-standards-standard-g
            zip_file: m-s-standards-standard-g.zip
      - name: /standards/{standard_id} put lambda deploy zip
        uses: postman-open-technologies/standards@main
        with:
            args: zip -qq -r m-s-standards-standard-pu.zip standards/standard_id/put/index.js node_modules
      - name: standard get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-standards-standard-pu
            zip_file: m-s-standards-standard-pu.zip
      - name: /standards/{standard_id} delete lambda deploy zip
        uses: postman-open-technologies/standards@main
        with:
            args: zip -qq -r m-s-standards-standard-d.zip standards/standard_id/delete/index.js node_modules
      - name: standard get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-standards-standard-d
            zip_file: m-s-standards-standard-d.zip          
      - name: /standards/{standard_id}/tags get lambda deploy zip
        uses: postman-open-technologies/standards@main
        with:
            args: zip -qq -r m-s-standards-standard-tags-g.zip standards/standard_id/tags/get/index.js node_modules
      - name: standards get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-standards-standard-tags-g
            zip_file: m-s-standards-standard-tags-g.zip
      - name: /standards/{standard_id}/tags post lambda deploy zip
        uses: postman-open-technologies/standards@main
        with:
            args: zip -qq -r m-s-standards-standard-tags-po.zip standards/standard_id/tags/post/index.js node_modules
      - name: standards get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-standards-standard-tags-po
            zip_file: m-s-standards-standard-tags-po.zip
      - name: /standards/{standard_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/standards@main
        with:
            args: zip -qq -r m-s-standards-standard-tags-tag-d.zip standards/standard_id/tags/tag_id/delete/index.js node_modules
      - name: standards get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-standards-standard-tags-tag-d
            zip_file: m-s-standards-standard-tags-tag-d.zip            
